-- =====================================================
-- 2026-08-10  119 신고 접수 표기 정정 + 송수신 로그 테이블
--
-- 적용 대상: 이 날짜 이전에 db/schema.sql 로 만든 기존 개발 DB
-- 새로 만드는 DB 는 db/schema.sql 하나면 되고 이 파일은 필요 없다.
--
-- 실행:
--   psql -U postgres -d fireguard -f db/migrations/001-2026-08-10-report-accepted-and-report-log.sql
--   (또는 pgAdmin Query Tool 에 통째로 붙여넣기)
--
-- 전체가 한 트랜잭션이다. 중간에 실패하면 아무것도 반영되지 않는다.
-- 이미 적용한 DB 에 다시 돌리면 1) 에서 오류가 나며 전부 롤백된다 — 안전하다.
--
-- 바뀌는 것 세 가지
--   1. 신고 상태 DISPATCHED → ACCEPTED,
--      report_119.report_dispatched_at → report_accepted_at
--      2xx 응답은 "119 가 신고를 받았다"이지 "소방차가 배차됐다"가 아니다.
--      출동 배차 확인은 119 가 별도 콜백으로 주는 값이고 아직 구현하지 않았다.
--   2. 부분 유니크 인덱스 재생성
--      인덱스 조건에 'DISPATCHED' 문자열이 직접 박혀 있다. 다시 만들지 않으면
--      ACCEPTED 행이 인덱스에 안 걸려서 이벤트당 진행 중 신고 1건 보장이
--      조용히 깨진다. 이 단계를 건너뛰면 안 된다.
--   3. report_log 테이블 신설 (ERD v4 에 없던 것)
--      119 로 전송한 시도 1회에 1행. 무엇을 보내고 무엇을 받았는지 남긴다.
--      report_119 는 결과 요약만 갖고 있어서 "몇 시에 뭘 보냈고 뭐라고 답이
--      왔길래 승계했나"를 사후에 따질 수 없었다. (요구사항 N-04)
-- =====================================================
BEGIN;

-- -----------------------------------------------------
-- 1) 상태값과 컬럼 이름
-- -----------------------------------------------------
ALTER TABLE fireguard.report_119
    RENAME COLUMN report_dispatched_at TO report_accepted_at;

UPDATE fireguard.report_119
    SET report_status = 'ACCEPTED' WHERE report_status = 'DISPATCHED';

COMMENT ON COLUMN fireguard.report_119.report_accepted_at
    IS '119 접수 확인 일시 (출동 배차 확인이 아님)';


-- -----------------------------------------------------
-- 2) 부분 유니크 인덱스 재생성
-- -----------------------------------------------------
DROP INDEX IF EXISTS fireguard.ux_report_119_active;
CREATE UNIQUE INDEX UX_report_119_active ON fireguard.report_119 (event_no)
    WHERE report_status IN ('SENDING', 'ACCEPTED');


-- -----------------------------------------------------
-- 3) 119 송수신 로그
-- log_result : ACCEPTED(2xx 접수확인) REJECTED(2xx 아닌 응답)
--              TIMEOUT(응답 없음 — 상대는 접수했을 수 있다)
--              ERROR(연결 실패 등 전송 자체가 안 됨)
-- -----------------------------------------------------
CREATE TABLE fireguard.report_log (
    log_no          bigint        GENERATED BY DEFAULT AS IDENTITY,
    report_no       bigint        NOT NULL,
    log_attempt     integer       NOT NULL,
    log_endpoint    varchar(500)  NULL,
    log_request     jsonb         NULL,
    log_result      varchar(20)   NULL,
    log_http_status integer       NULL,
    log_response    jsonb         NULL,
    log_error       varchar(500)  NULL,
    log_elapsed_ms  integer       NULL,
    log_sent_at     timestamp     NULL
);

ALTER TABLE fireguard.report_log ADD CONSTRAINT PK_REPORT_LOG PRIMARY KEY (log_no);

ALTER TABLE fireguard.report_log ADD CONSTRAINT FK_report_119_TO_report_log
    FOREIGN KEY (report_no) REFERENCES fireguard.report_119 (report_no);

CREATE INDEX IX_report_log_01 ON fireguard.report_log (report_no, log_attempt);

COMMENT ON TABLE  fireguard.report_log                 IS '119 송수신 로그';
COMMENT ON COLUMN fireguard.report_log.log_no          IS '로그 번호';
COMMENT ON COLUMN fireguard.report_log.report_no       IS '신고 번호';
COMMENT ON COLUMN fireguard.report_log.log_attempt     IS '몇 번째 전송 시도인가';
COMMENT ON COLUMN fireguard.report_log.log_endpoint    IS '전송한 기관 주소';
COMMENT ON COLUMN fireguard.report_log.log_request     IS '보낸 신고 본문';
COMMENT ON COLUMN fireguard.report_log.log_result      IS '전송 결과';
COMMENT ON COLUMN fireguard.report_log.log_http_status IS '응답 HTTP 상태코드 (무응답이면 없음)';
COMMENT ON COLUMN fireguard.report_log.log_response    IS '받은 응답 본문';
COMMENT ON COLUMN fireguard.report_log.log_error       IS '전송 실패 사유 (타임아웃·연결실패)';
COMMENT ON COLUMN fireguard.report_log.log_elapsed_ms  IS '요청부터 응답까지 걸린 시간(ms)';
COMMENT ON COLUMN fireguard.report_log.log_sent_at     IS '전송 일시';

COMMIT;


-- =====================================================
-- 적용 확인 (선택) — 아래를 실행해 세 가지를 눈으로 확인한다
-- =====================================================
-- SELECT report_status, count(*) FROM fireguard.report_119 GROUP BY 1;
--   → DISPATCHED 가 하나도 없어야 한다
-- SELECT indexdef FROM pg_indexes
--  WHERE schemaname='fireguard' AND indexname='ux_report_119_active';
--   → 조건이 ('SENDING','ACCEPTED') 여야 한다
-- SELECT count(*) FROM fireguard.report_log;
--   → 0 (테이블이 있으면 성공)
