-- =====================================================
-- 2026-08-14  사용자 활동이력 테이블 신설
--
-- 적용 대상: 이 날짜 이전에 db/schema.sql 로 만든 기존 개발 DB
-- 새로 만드는 DB 는 db/schema.sql 하나면 되고 이 파일은 필요 없다.
--
-- 실행:
--   psql -U postgres -d fireguard -f db/migrations/005-2026-08-14-user-activity.sql
--   (또는 pgAdmin Query Tool 에 통째로 붙여넣기)
--
-- 전체가 한 트랜잭션이다. 중간에 실패하면 아무것도 반영되지 않는다.
-- 이미 적용한 DB 에 다시 돌리면 CREATE TABLE 에서 오류가 나며 전부 롤백된다 — 안전하다.
--
-- 바뀌는 것 한 가지
--   user_activity 테이블 신설 (ERD v4 에 없던 것)
--   사용자 1명에 N행. 남기는 종류는 두 가지뿐이다 — LOGIN(접속) / LOGOUT(로그아웃).
--   그동안 users 에는 가입·수정·탈퇴 일시만 있어서 "이 사람이 언제 들어왔나"를
--   답할 근거가 아예 없었다. 프론트의 회원 상세 화면(최근 로그인 / 활동 이력)이
--   지금 localStorage 로 버티고 있는 것도 이 표가 없어서다.
--
-- 넣지 않기로 한 것: IP, User-Agent
--   "들어왔다 / 나갔다"만 보여주기로 정했다. 나중에 필요해지면 컬럼을 더하면 되지만,
--   그 시점의 기존 행은 전부 NULL 로 남는다는 점은 알고 있어야 한다.
--
-- 로그인 실패는 여기 쌓지 않는다. 실패는 침입 시도 기록이지 접속 이력이 아니고,
-- 한 표에 섞이면 '이 사람이 언제 들어왔나'를 읽을 수 없게 된다.
--
-- ⚠️ JWT 는 무상태라 서버가 로그아웃 시점을 스스로 알 수 없다. LOGOUT 행은
--    프론트가 POST /api/auth/logout 을 불러줘야만 쌓인다. 브라우저를 그냥 닫으면
--    남지 않는다 — 명시적 로그아웃만 기록되는 표다.
-- =====================================================
BEGIN;

CREATE TABLE fireguard.user_activity (
    activity_no   bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_no       bigint       NOT NULL,
    activity_type varchar(20)  NOT NULL,
    activity_at   timestamp    NOT NULL  DEFAULT now()
);

ALTER TABLE fireguard.user_activity
    ADD CONSTRAINT PK_USER_ACTIVITY PRIMARY KEY (activity_no);

ALTER TABLE fireguard.user_activity ADD CONSTRAINT FK_users_TO_user_activity
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);

-- 화면이 항상 "이 사람의 최근 이력"을 최신순으로 뽑으므로 정렬 방향까지 맞춰 둔다
CREATE INDEX IX_user_activity_01 ON fireguard.user_activity (user_no, activity_at DESC);

COMMENT ON TABLE  fireguard.user_activity               IS '사용자 활동이력';
COMMENT ON COLUMN fireguard.user_activity.activity_no   IS '활동 번호';
COMMENT ON COLUMN fireguard.user_activity.user_no       IS '사용자 번호';
COMMENT ON COLUMN fireguard.user_activity.activity_type IS '활동 종류';
COMMENT ON COLUMN fireguard.user_activity.activity_at   IS '활동 일시';

COMMIT;


-- =====================================================
-- 적용 확인 (선택)
-- =====================================================
-- SELECT count(*) FROM fireguard.user_activity;
--   → 0 (테이블이 있으면 성공)
-- SELECT indexdef FROM pg_indexes
--  WHERE schemaname='fireguard' AND indexname='ix_user_activity_01';
--   → (user_no, activity_at DESC) 여야 한다
