-- =====================================================
-- 파이어가드 (Fire Prevention and Detection)
-- PostgreSQL 구축 스크립트  |  ERD v4 기반, 테이블 8개
-- (report_log 는 ERD v4 에 없던 것 — 119 송수신 이력을 남기려고 추가했다)
--
-- ⚠️ 이 파일은 DB 를 처음부터 만드는 용도다. 아래 DROP SCHEMA 가
--    fireguard 스키마를 통째로 지우므로 기존 데이터는 전부 사라진다.
--    fireguard 스키마 안에 PostGIS 를 설치해 뒀다면 그 확장도 같이 날아간다.
--    이미 쓰고 있는 DB 를 최신 구조로 맞추려면 db/migrations/ 의 파일을 쓸 것.
--
-- =====================================================
DROP SCHEMA IF EXISTS fireguard CASCADE;

-- =====================================================
-- 0. 스키마
-- =====================================================
CREATE SCHEMA IF NOT EXISTS fireguard;

-- 이 세션 동안 스키마 이름을 생략할 수 있게 한다
-- (Query Tool 을 새로 열면 초기화되므로 다시 실행해야 한다)
SET search_path TO fireguard, public;


-- -----------------------------------------------------
-- 1. 관리자 계정                                  [F-01]
-- -----------------------------------------------------
CREATE TABLE fireguard.users (
    user_no            bigint        GENERATED BY DEFAULT AS IDENTITY,
    user_id            varchar(50)   NOT NULL,
    user_pw            varchar(255)  NOT NULL,
    user_name          varchar(50)   NULL,
    user_email         varchar(100)  NULL,
    user_phone         varchar(20)   NULL,
    user_role          varchar(20)   NULL,
    user_status        varchar(20)   NULL,
    user_gender        varchar(10)   NULL,
    user_address       varchar(255)  NULL,
    user_created_at    timestamp     NULL  DEFAULT now(),
    user_updated_at    timestamp     NULL,
    user_withdrawal_at timestamp     NULL
);


-- -----------------------------------------------------
-- 2. 연동 카메라                             [F-02 F-08]
-- 신고 기관 선정의 기준 좌표가 여기에 있다
-- -----------------------------------------------------
CREATE TABLE fireguard.cctv (
    cctv_no         bigint         GENERATED BY DEFAULT AS IDENTITY,
    user_no         bigint         NOT NULL,
    cctv_name       varchar(100)   NULL,
    cctv_location   varchar(255)   NULL,
    cctv_lat        numeric(10,7)  NULL,
    cctv_lng        numeric(10,7)  NULL,
    cctv_stream_url varchar(500)   NULL,
    cctv_width      integer        NULL,
    cctv_height     integer        NULL,
    cctv_status     varchar(20)    NULL,
    cctv_created_at timestamp      NULL  DEFAULT now()
);


-- -----------------------------------------------------
-- 3. 화재 판정 결과                         [F-03 F-06]
-- -----------------------------------------------------
CREATE TABLE fireguard.fire_event (
    event_no                bigint        GENERATED BY DEFAULT AS IDENTITY,
    cctv_no                 bigint        NOT NULL,
    event_status            varchar(20)   NULL,
    event_class             varchar(20)   NULL,
    event_first_detected_at timestamp     NULL,
    event_detected_at       timestamp     NULL,
    event_detected_frames   integer       NULL,
    event_threshold_frames  integer       NULL,
    event_confidence        numeric(5,4)  NULL,
    event_is_test           boolean       NOT NULL  DEFAULT false
);


-- -----------------------------------------------------
-- 4. 검출 프레임과 영상 클립                  [F-02 F-06]
-- -----------------------------------------------------
CREATE TABLE fireguard.event_media (
    media_no          bigint        GENERATED BY DEFAULT AS IDENTITY,
    event_no          bigint        NOT NULL,
    media_type        varchar(20)   NULL,
    media_url         varchar(500)  NULL,
    media_detections  jsonb         NULL,
    media_confidence  numeric(5,4)  NULL,
    media_captured_at timestamp     NULL,
    media_is_primary  boolean       NOT NULL  DEFAULT false
);


-- -----------------------------------------------------
-- 5. 단계별 관리자 알림                            [F-04]
-- -----------------------------------------------------
CREATE TABLE fireguard.alert (
    alert_no           bigint       GENERATED BY DEFAULT AS IDENTITY,
    event_no           bigint       NOT NULL,
    user_no            bigint       NOT NULL,
    alert_level        integer      NULL,
    alert_channel      varchar(20)  NULL,
    alert_status       varchar(20)  NULL,
    alert_sent_at      timestamp    NULL,
    alert_deadline_at  timestamp    NULL,
    alert_responded_at timestamp    NULL
);


-- -----------------------------------------------------
-- 6. 소방서                                      [F-05]
-- 승계 우선순위는 컬럼으로 두지 않는다
-- CCTV 좌표에서의 거리로 매번 산정한다
-- agency_endpoint 는 가상 119 서버 주소가 들어간다
-- -----------------------------------------------------
CREATE TABLE fireguard.agency (
    agency_no       bigint         GENERATED BY DEFAULT AS IDENTITY,
    agency_name     varchar(100)   NULL,
    agency_lat      numeric(10,7)  NULL,
    agency_lng      numeric(10,7)  NULL,
    agency_endpoint varchar(255)   NULL,
    agency_is_active boolean       NOT NULL  DEFAULT true
);


-- -----------------------------------------------------
-- 7. 119 신고                               [F-05 F-09]
-- 이벤트 1건에 여러 행이 쌓인다 (승계 이력)
-- report_sequence      기관을 몇 번째로 바꿨나 (바깥 루프)
-- report_attempt_count 그 기관에 몇 번 쐈나 (안쪽 루프, 최대 4)
-- -----------------------------------------------------
CREATE TABLE fireguard.report_119 (
    report_no             bigint        GENERATED BY DEFAULT AS IDENTITY,
    event_no              bigint        NOT NULL,
    agency_no             bigint        NOT NULL,
    report_sequence       integer       NULL,
    report_external_id    varchar(50)   NULL,
    report_trigger_reason varchar(100)  NULL,
    report_status         varchar(20)   NULL,
    report_address        varchar(255)  NULL,
    report_distance_km    numeric(6,3)  NULL,
    report_attempt_count  integer       NULL  DEFAULT 0,
    reported_at           timestamp     NULL,
    report_accepted_at    timestamp     NULL
);


-- -----------------------------------------------------
-- 8. 119 송수신 로그                          [F-05 N-04]
-- 전송 시도 1회에 1행. 무엇을 보냈고 무엇이 돌아왔는지 그대로 남긴다.
-- report_119 는 결과 요약(상태·시도횟수·접수번호)만 갖고 있어서
-- "언제 보냈고 왜 승계했나"를 사후에 따질 근거가 없었다.
-- 응답이 없어 재전송한 것과 거절당해 재전송한 것은 뜻이 다르다 — log_result 로 구분한다.
-- -----------------------------------------------------
CREATE TABLE fireguard.report_log (
    log_no          bigint        GENERATED BY DEFAULT AS IDENTITY,
    report_no       bigint        NOT NULL,
    log_attempt     integer       NOT NULL,
    log_endpoint    varchar(500)  NULL,
    log_request     jsonb         NULL,
    log_result      varchar(20)   NULL,
    log_http_status integer       NULL,
    log_response    jsonb         NULL,
    log_error       varchar(500)  NULL,
    log_elapsed_ms  integer       NULL,
    log_sent_at     timestamp     NULL
);


-- =====================================================
-- 기본키
-- =====================================================
ALTER TABLE fireguard.users      ADD CONSTRAINT PK_USERS       PRIMARY KEY (user_no);
ALTER TABLE fireguard.cctv       ADD CONSTRAINT PK_CCTV        PRIMARY KEY (cctv_no);
ALTER TABLE fireguard.fire_event ADD CONSTRAINT PK_FIRE_EVENT  PRIMARY KEY (event_no);
ALTER TABLE fireguard.event_media ADD CONSTRAINT PK_EVENT_MEDIA PRIMARY KEY (media_no);
ALTER TABLE fireguard.alert      ADD CONSTRAINT PK_ALERT       PRIMARY KEY (alert_no);
ALTER TABLE fireguard.agency     ADD CONSTRAINT PK_AGENCY      PRIMARY KEY (agency_no);
ALTER TABLE fireguard.report_119 ADD CONSTRAINT PK_REPORT_119  PRIMARY KEY (report_no);
ALTER TABLE fireguard.report_log ADD CONSTRAINT PK_REPORT_LOG  PRIMARY KEY (log_no);


-- =====================================================
-- 유니크 제약
-- 로그인 아이디 중복을 DB 에서 막는다 (ERD v4 에는 없던 것)
-- =====================================================
ALTER TABLE fireguard.users ADD CONSTRAINT UQ_USERS_USER_ID UNIQUE (user_id);


-- =====================================================
-- 외래키
-- =====================================================
ALTER TABLE fireguard.cctv ADD CONSTRAINT FK_users_TO_cctv
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);

ALTER TABLE fireguard.fire_event ADD CONSTRAINT FK_cctv_TO_fire_event
    FOREIGN KEY (cctv_no) REFERENCES fireguard.cctv (cctv_no);

ALTER TABLE fireguard.event_media ADD CONSTRAINT FK_fire_event_TO_event_media
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.alert ADD CONSTRAINT FK_fire_event_TO_alert
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.alert ADD CONSTRAINT FK_users_TO_alert
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);

ALTER TABLE fireguard.report_119 ADD CONSTRAINT FK_fire_event_TO_report_119
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.report_119 ADD CONSTRAINT FK_agency_TO_report_119
    FOREIGN KEY (agency_no) REFERENCES fireguard.agency (agency_no);

ALTER TABLE fireguard.report_log ADD CONSTRAINT FK_report_119_TO_report_log
    FOREIGN KEY (report_no) REFERENCES fireguard.report_119 (report_no);


-- =====================================================
-- 인덱스
-- =====================================================
CREATE INDEX IX_fire_event_01  ON fireguard.fire_event  (cctv_no, event_detected_at);
CREATE INDEX IX_event_media_01 ON fireguard.event_media (event_no, media_is_primary);
CREATE INDEX IX_alert_01       ON fireguard.alert       (event_no, alert_level);
CREATE INDEX IX_report_119_01  ON fireguard.report_119  (event_no, report_sequence);
CREATE INDEX IX_report_log_01  ON fireguard.report_log  (report_no, log_attempt);

-- 진행 중인 신고가 이벤트당 하나만 있도록 DB 에서 강제한다
-- PostgreSQL 부분 인덱스 (MySQL 에는 없는 기능)
CREATE UNIQUE INDEX UX_report_119_active ON fireguard.report_119 (event_no)
    WHERE report_status IN ('SENDING', 'ACCEPTED');


-- =====================================================
-- 테이블 주석 (pgAdmin 트리와 ERD 도구에서 한글 논리명으로 보인다)
-- =====================================================
COMMENT ON TABLE fireguard.users       IS '관리자 계정';
COMMENT ON TABLE fireguard.cctv        IS '연동 카메라';
COMMENT ON TABLE fireguard.fire_event  IS '화재 판정 결과';
COMMENT ON TABLE fireguard.event_media IS '검출 프레임과 영상 클립';
COMMENT ON TABLE fireguard.alert       IS '단계별 관리자 알림';
COMMENT ON TABLE fireguard.agency      IS '소방서';
COMMENT ON TABLE fireguard.report_119  IS '119 신고';
COMMENT ON TABLE fireguard.report_log  IS '119 송수신 로그';


-- =====================================================
-- 컬럼 주석
-- =====================================================
COMMENT ON COLUMN fireguard.users.user_no            IS '사용자 번호';
COMMENT ON COLUMN fireguard.users.user_id            IS '로그인 아이디';
COMMENT ON COLUMN fireguard.users.user_pw            IS '비밀번호 해시';
COMMENT ON COLUMN fireguard.users.user_name          IS '이름';
COMMENT ON COLUMN fireguard.users.user_email         IS '이메일';
COMMENT ON COLUMN fireguard.users.user_phone         IS '휴대전화 번호';
COMMENT ON COLUMN fireguard.users.user_role          IS '권한 등급';
COMMENT ON COLUMN fireguard.users.user_status        IS '계정 상태';
COMMENT ON COLUMN fireguard.users.user_gender        IS '성별';
COMMENT ON COLUMN fireguard.users.user_address       IS '주소';
COMMENT ON COLUMN fireguard.users.user_created_at    IS '가입 일시';
COMMENT ON COLUMN fireguard.users.user_updated_at    IS '수정 일시';
COMMENT ON COLUMN fireguard.users.user_withdrawal_at IS '탈퇴 일시';

COMMENT ON COLUMN fireguard.cctv.cctv_no         IS '카메라 번호';
COMMENT ON COLUMN fireguard.cctv.user_no         IS '담당 사용자 번호';
COMMENT ON COLUMN fireguard.cctv.cctv_name       IS '카메라 이름';
COMMENT ON COLUMN fireguard.cctv.cctv_location   IS '설치 위치';
COMMENT ON COLUMN fireguard.cctv.cctv_lat        IS '위도';
COMMENT ON COLUMN fireguard.cctv.cctv_lng        IS '경도';
COMMENT ON COLUMN fireguard.cctv.cctv_stream_url IS '스트림 주소';
COMMENT ON COLUMN fireguard.cctv.cctv_width      IS '영상 가로 픽셀';
COMMENT ON COLUMN fireguard.cctv.cctv_height     IS '영상 세로 픽셀';
COMMENT ON COLUMN fireguard.cctv.cctv_status     IS '카메라 상태';
COMMENT ON COLUMN fireguard.cctv.cctv_created_at IS '등록 일시';

COMMENT ON COLUMN fireguard.fire_event.event_no                IS '이벤트 번호';
COMMENT ON COLUMN fireguard.fire_event.cctv_no                 IS '카메라 번호';
COMMENT ON COLUMN fireguard.fire_event.event_status            IS '판정 결과';
COMMENT ON COLUMN fireguard.fire_event.event_class             IS '검출 종류';
COMMENT ON COLUMN fireguard.fire_event.event_first_detected_at IS '최초 감지 일시';
COMMENT ON COLUMN fireguard.fire_event.event_detected_at       IS '화재 확정 일시';
COMMENT ON COLUMN fireguard.fire_event.event_detected_frames   IS '검출된 프레임 수';
COMMENT ON COLUMN fireguard.fire_event.event_threshold_frames  IS '확정 기준 프레임 수';
COMMENT ON COLUMN fireguard.fire_event.event_confidence        IS '최고 신뢰도';
COMMENT ON COLUMN fireguard.fire_event.event_is_test           IS '점검 모드 여부';

COMMENT ON COLUMN fireguard.event_media.media_no          IS '미디어 번호';
COMMENT ON COLUMN fireguard.event_media.event_no          IS '이벤트 번호';
COMMENT ON COLUMN fireguard.event_media.media_type        IS '미디어 종류';
COMMENT ON COLUMN fireguard.event_media.media_url         IS '파일 경로';
COMMENT ON COLUMN fireguard.event_media.media_detections  IS '검출 상자 목록';
COMMENT ON COLUMN fireguard.event_media.media_confidence  IS '최고 신뢰도';
COMMENT ON COLUMN fireguard.event_media.media_captured_at IS '촬영 일시';
COMMENT ON COLUMN fireguard.event_media.media_is_primary  IS '대표 이미지 여부';

COMMENT ON COLUMN fireguard.alert.alert_no           IS '알림 번호';
COMMENT ON COLUMN fireguard.alert.event_no           IS '이벤트 번호';
COMMENT ON COLUMN fireguard.alert.user_no            IS '수신 사용자 번호';
COMMENT ON COLUMN fireguard.alert.alert_level        IS '알림 단계';
COMMENT ON COLUMN fireguard.alert.alert_channel      IS '발송 경로';
COMMENT ON COLUMN fireguard.alert.alert_status       IS '알림 상태';
COMMENT ON COLUMN fireguard.alert.alert_sent_at      IS '발송 일시';
COMMENT ON COLUMN fireguard.alert.alert_deadline_at  IS '취소 유예 마감 일시';
COMMENT ON COLUMN fireguard.alert.alert_responded_at IS '응답 일시';

COMMENT ON COLUMN fireguard.agency.agency_no       IS '기관 번호';
COMMENT ON COLUMN fireguard.agency.agency_name     IS '기관 이름';
COMMENT ON COLUMN fireguard.agency.agency_lat      IS '위도';
COMMENT ON COLUMN fireguard.agency.agency_lng      IS '경도';
COMMENT ON COLUMN fireguard.agency.agency_endpoint IS '신고 전송 주소';
COMMENT ON COLUMN fireguard.agency.agency_is_active IS '기관 사용 여부';

COMMENT ON COLUMN fireguard.report_119.report_no             IS '신고 번호';
COMMENT ON COLUMN fireguard.report_119.event_no              IS '이벤트 번호';
COMMENT ON COLUMN fireguard.report_119.agency_no             IS '전송 대상 기관 번호';
COMMENT ON COLUMN fireguard.report_119.report_sequence       IS '승계 순번';
COMMENT ON COLUMN fireguard.report_119.report_external_id    IS '신고 식별자';
COMMENT ON COLUMN fireguard.report_119.report_trigger_reason IS '신고 발생 사유';
COMMENT ON COLUMN fireguard.report_119.report_status         IS '신고 상태';
COMMENT ON COLUMN fireguard.report_119.report_address        IS '신고 지점 주소';
COMMENT ON COLUMN fireguard.report_119.report_distance_km    IS '기관까지 거리';
COMMENT ON COLUMN fireguard.report_119.report_attempt_count  IS '전송 시도 횟수';
COMMENT ON COLUMN fireguard.report_119.reported_at           IS '전송 일시';
COMMENT ON COLUMN fireguard.report_119.report_accepted_at    IS '119 접수 확인 일시 (출동 배차 확인이 아님)';

COMMENT ON COLUMN fireguard.report_log.log_no          IS '로그 번호';
COMMENT ON COLUMN fireguard.report_log.report_no       IS '신고 번호';
COMMENT ON COLUMN fireguard.report_log.log_attempt     IS '몇 번째 전송 시도인가';
COMMENT ON COLUMN fireguard.report_log.log_endpoint    IS '전송한 기관 주소';
COMMENT ON COLUMN fireguard.report_log.log_request     IS '보낸 신고 본문';
COMMENT ON COLUMN fireguard.report_log.log_result      IS '전송 결과';
COMMENT ON COLUMN fireguard.report_log.log_http_status IS '응답 HTTP 상태코드 (무응답이면 없음)';
COMMENT ON COLUMN fireguard.report_log.log_response    IS '받은 응답 본문';
COMMENT ON COLUMN fireguard.report_log.log_error       IS '전송 실패 사유 (타임아웃·연결실패)';
COMMENT ON COLUMN fireguard.report_log.log_elapsed_ms  IS '요청부터 응답까지 걸린 시간(ms)';
COMMENT ON COLUMN fireguard.report_log.log_sent_at     IS '전송 일시';


-- =====================================================
-- 상태값 정의 (참고용, 코드에서 비교하는 값)
-- =====================================================
-- users.user_role          : ADMIN(관리자) VIEWER(조회전용)
-- users.user_status        : ACTIVE(정상) SUSPENDED(정지) WITHDRAWN(탈퇴)
-- cctv.cctv_status         : ACTIVE(정상) INACTIVE(중지) ERROR(오류)
-- fire_event.event_status  : PENDING(누적중) CONFIRMED(확정) DISMISSED(기준미달)
-- fire_event.event_class   : FLAME(불꽃) SMOKE(연기) FLAME_SMOKE(둘다)
-- event_media.media_type   : FRAME(프레임 이미지)
--                            (CLIP(영상 클립)은 2026-08-10 폐기 — 프레임만 저장한다)
-- alert.alert_level        : 항상 1 (승격 단계 폐기 — 컬럼은 스키마 호환용)
-- alert.alert_channel      : PUSH(앱알림) SMS(문자)
-- alert.alert_status       : SENT(발송) READ(확인) CANCELED(취소) NO_RESPONSE(무응답)
-- report_119.report_status : SENDING(전송중) ACCEPTED(접수확인)
--                            NO_RESPONSE(무응답으로 승계) FAILED(전송실패)
-- report_log.log_result    : ACCEPTED(2xx 접수확인) REJECTED(2xx 아닌 응답)
--                            TIMEOUT(응답 없음 — 상대는 접수했을 수 있다)
--                            ERROR(연결 실패 등 전송 자체가 안 됨)
--
-- media_detections 저장 형태 (좌표는 0~1 비율, YOLO 의 xywhn)
-- [{"cls":"flame","conf":0.910,"box":[0.238,0.259,0.047,0.113]},
--  {"cls":"person","conf":0.774,"box":[0.412,0.688,0.031,0.142]}]


-- =====================================================
-- 구축 확인
-- =====================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'fireguard'
ORDER BY table_name;

select * from cctv;

