-- =====================================================
-- 파이어가드 (Fire Prevention and Detection)
-- PostgreSQL 구축 스크립트  |  ERD v4 기반, 테이블 9개
-- (report_log 는 ERD v4 에 없던 것 — 119 송수신 이력을 남기려고 추가했다)
-- (user_activity 도 ERD v4 에 없던 것 — 접속·로그아웃 이력을 남기려고 추가했다)
--
-- ⚠️ 이 파일은 DB 를 처음부터 만드는 용도다. 아래 DROP SCHEMA 가
--    fireguard 스키마를 통째로 지우므로 기존 데이터는 전부 사라진다.
--    이미 쓰고 있는 DB 를 최신 구조로 맞추려면 db/migrations/ 의 파일을 쓸 것.
--
-- 📦 PostGIS 3 이 필요하다 (최근접 소방서 탐색에 쓴다). 설치 방법은
--    back/docs/team-setup.html 참고. CREATE EXTENSION 에는 superuser 권한이 든다.
--
-- =====================================================

DROP SCHEMA IF EXISTS fireguard CASCADE;

-- =====================================================
-- 0. 공간 확장 — 반드시 public 에 설치한다
--
-- fireguard 스키마 안에 설치하면 위 DROP SCHEMA CASCADE 가 확장까지 지워버린다.
-- 그래서 확장은 지워지지 않는 public 에 두고, 함수는 public. 을 붙여 부른다.
--
-- ⚠️ 순서가 중요하다. DROP SCHEMA 를 **먼저** 하고 그 다음에 확장을 만든다.
--    반대로 하면, 확장이 이미 fireguard 안에 있는 DB 에서 IF NOT EXISTS 가
--    '있으니 통과'로 넘어간 뒤 DROP SCHEMA 가 그 확장을 지워버려서
--    아래 public.ST_MakePoint 호출이 전부 깨진다.
--    이 순서 덕에 확장이 어디에 있었든 실행 후에는 public 에 놓인다.
--
-- ※ PostGIS 는 재배치가 안 되는 확장이라 ALTER EXTENSION ... SET SCHEMA 로는
--    옮길 수 없다. 기존 DB 를 옮기는 방법은 db/migrations/ 쪽에 있다.
-- =====================================================
CREATE EXTENSION IF NOT EXISTS postgis SCHEMA public;

-- =====================================================
-- 0-1. 스키마
-- =====================================================
CREATE SCHEMA IF NOT EXISTS fireguard;

-- 이 세션 동안 스키마 이름을 생략할 수 있게 한다
-- (Query Tool 을 새로 열면 초기화되므로 다시 실행해야 한다)
SET search_path TO fireguard, public;


-- -----------------------------------------------------
-- 1. 관리자 계정                                  [F-01]
-- -----------------------------------------------------
-- user_pw 가 NULL 일 수 있다 — 소셜 로그인 계정은 비밀번호를 갖지 않는다.
-- 대신 CK_USERS_LOCAL_PW 로 "일반(LOCAL) 계정이면 비밀번호 필수"를 강제한다.
CREATE TABLE fireguard.users (
    user_no            bigint        GENERATED BY DEFAULT AS IDENTITY,
    user_id            varchar(50)   NOT NULL,
    user_pw            varchar(255)  NULL,
    user_name          varchar(50)   NULL,
    user_email         varchar(100)  NULL,
    user_phone         varchar(20)   NULL,
    user_role          varchar(20)   NULL,
    user_status        varchar(20)   NULL,
    user_gender        varchar(10)   NULL,
    user_address       varchar(255)  NULL,
    user_provider      varchar(20)   NOT NULL  DEFAULT 'LOCAL',
    user_provider_id   varchar(191)  NULL,
    user_token_valid_from timestamp  NULL,
    user_created_at    timestamp     NULL  DEFAULT now(),
    user_updated_at    timestamp     NULL,
    user_withdrawal_at timestamp     NULL
);


-- -----------------------------------------------------
-- 2. 연동 카메라                             [F-02 F-08]
-- 신고 기관 선정의 기준 좌표가 여기에 있다
-- -----------------------------------------------------
CREATE TABLE fireguard.cctv (
    cctv_no         bigint         GENERATED BY DEFAULT AS IDENTITY,
    user_no         bigint         NOT NULL,
    cctv_name       varchar(100)   NULL,
    cctv_location   varchar(255)   NULL,
    -- 좌표를 역지오코딩한 주소. 119 신고에 싣는 값이다.
    -- cctv_location 은 사람이 붙인 설치 위치 설명('본관 정문 앞')이거나 ITS 카메라
    -- 이름('[수도권제1순환선] 판교분기점')이라 소방 지령에 쓸 수 없다.
    -- CCTV 등록 시점에 한 번 채운다 — 신고 순간에 외부 API 를 부르면 그 지연이
    -- 그대로 119 전송 지연이 된다 (신고는 동기 경로다).
    cctv_address    varchar(255)   NULL,
    cctv_lat        numeric(10,7)  NULL,
    cctv_lng        numeric(10,7)  NULL,
    cctv_stream_url varchar(500)   NULL,
    cctv_width      integer        NULL,
    cctv_height     integer        NULL,
    cctv_status     varchar(20)    NULL,
    cctv_created_at timestamp      NULL  DEFAULT now(),
    -- 공간 질의용 좌표점. 위경도에서 자동 파생되는 생성 컬럼이라 앱이 채우지 않는다
    -- (원본과 어긋날 수가 없다). ST_MakePoint 는 경도·위도 순서임에 주의.
    cctv_geog       public.geography(Point,4326)
        GENERATED ALWAYS AS (
            public.ST_SetSRID(
                public.ST_MakePoint(cctv_lng::double precision,
                                    cctv_lat::double precision), 4326
            )::public.geography
        ) STORED
);


-- -----------------------------------------------------
-- 3. 화재 판정 결과                         [F-03 F-06]
-- -----------------------------------------------------
CREATE TABLE fireguard.fire_event (
    event_no                bigint        GENERATED BY DEFAULT AS IDENTITY,
    cctv_no                 bigint        NOT NULL,
    event_status            varchar(20)   NULL,
    event_class             varchar(20)   NULL,
    event_first_detected_at timestamp     NULL,
    event_detected_at       timestamp     NULL,
    event_detected_frames   integer       NULL,
    event_threshold_frames  integer       NULL,
    event_confidence        numeric(5,4)  NULL,
    event_is_test           boolean       NOT NULL  DEFAULT false,
    -- CCTV 실시간 수집과 업로드 영상 테스트를 같은 이벤트 테이블에서 구분한다.
    event_source_type       varchar(20)   NOT NULL  DEFAULT 'CCTV_LIVE',
    event_source_metadata   jsonb         NULL,
    -- 테스트 당시 CCTV 정보. 이후 CCTV 이름/주소가 바뀌어도 이력은 그대로 남는다.
    event_cctv_snapshot     jsonb         NULL,
    event_processed_frames  integer       NULL,
    event_first_detected_offset_sec numeric(12,3) NULL,
    event_confirmed_offset_sec      numeric(12,3) NULL,
    event_test_started_at   timestamp     NULL,
    event_test_finished_at  timestamp     NULL
);


-- -----------------------------------------------------
-- 4. 검출 프레임                              [F-02 F-06]
-- 프레임만 저장한다 — CLIP(영상 클립)과 media_type 컬럼은
-- 2026-08-10 폐기 (항상 FRAME 이라 구분이 무의미)
-- -----------------------------------------------------
CREATE TABLE fireguard.event_media (
    media_no          bigint        GENERATED BY DEFAULT AS IDENTITY,
    event_no          bigint        NOT NULL,
    media_url         varchar(500)  NULL,
    media_detections  jsonb         NULL,
    media_confidence  numeric(5,4)  NULL,
    media_captured_at timestamp     NULL,
    media_is_primary  boolean       NOT NULL  DEFAULT false,
    media_is_first    boolean       NOT NULL  DEFAULT false,
    media_is_confirmation boolean   NOT NULL  DEFAULT false,
    media_frame_index bigint        NULL,
    media_source_offset_sec numeric(12,3) NULL
);


-- -----------------------------------------------------
-- 5. 관리자 알림                                  [F-04]
-- 승격 단계 폐기 — PUSH·SMS 두 채널 동시 발송.
-- alert_level 컬럼은 2026-08-10 삭제 (항상 1 이었음)
-- -----------------------------------------------------
CREATE TABLE fireguard.alert (
    alert_no           bigint       GENERATED BY DEFAULT AS IDENTITY,
    event_no           bigint       NOT NULL,
    user_no            bigint       NOT NULL,
    alert_channel      varchar(20)  NULL,
    alert_status       varchar(20)  NULL,
    alert_sent_at      timestamp    NULL,
    alert_deadline_at  timestamp    NULL,
    alert_responded_at timestamp    NULL
);


-- -----------------------------------------------------
-- 6. 소방서                                      [F-05]
-- 승계 우선순위는 컬럼으로 두지 않는다
-- CCTV 좌표에서의 거리로 매번 산정한다
-- agency_endpoint 는 가상 119 서버 주소가 들어간다
-- -----------------------------------------------------
CREATE TABLE fireguard.agency (
    agency_no       bigint         GENERATED BY DEFAULT AS IDENTITY,
    agency_name     varchar(100)   NULL,
    agency_lat      numeric(10,7)  NULL,
    agency_lng      numeric(10,7)  NULL,
    agency_endpoint varchar(255)   NULL,
    agency_is_active boolean       NOT NULL  DEFAULT true,
    -- 출처(생활안전지도 IF_0038)의 고유번호 objt_id. 손으로 등록한 행은 NULL.
    -- 같은 이름의 소방서가 전국에 여럿 있어(중부소방서 5곳 등) 이름으로는 기관을
    -- 가릴 수 없다 — 적재 스크립트는 이 값으로 기존 행을 찾는다.
    agency_source_id varchar(40)  NULL,
    agency_address  varchar(255)  NULL,
    agency_phone    varchar(30)   NULL,
    -- 최근접 소방서 탐색의 대상 좌표점 (cctv_geog 와 같은 방식의 생성 컬럼)
    agency_geog     public.geography(Point,4326)
        GENERATED ALWAYS AS (
            public.ST_SetSRID(
                public.ST_MakePoint(agency_lng::double precision,
                                    agency_lat::double precision), 4326
            )::public.geography
        ) STORED
);


-- -----------------------------------------------------
-- 7. 119 신고                               [F-05 F-09]
-- 이벤트 1건에 여러 행이 쌓인다 (승계 이력)
-- report_sequence      기관을 몇 번째로 바꿨나 (바깥 루프)
-- report_attempt_count 그 기관에 몇 번 쐈나 (안쪽 루프, 최대 4)
-- -----------------------------------------------------
CREATE TABLE fireguard.report_119 (
    report_no             bigint        GENERATED BY DEFAULT AS IDENTITY,
    event_no              bigint        NOT NULL,
    agency_no             bigint        NOT NULL,
    report_sequence       integer       NULL,
    report_external_id    varchar(50)   NULL,
    report_trigger_reason varchar(100)  NULL,
    report_status         varchar(20)   NULL,
    report_address        varchar(255)  NULL,
    report_distance_km    numeric(6,3)  NULL,
    report_attempt_count  integer       NULL  DEFAULT 0,
    reported_at           timestamp     NULL,
    report_accepted_at    timestamp     NULL,
    -- 소방서가 출동 통지를 보내온 시각과 그 원문.
    -- report_accepted_at(접수 확인)과 뜻이 다르다 — 접수는 '신고를 받았다',
    -- 출동은 '소방차가 나갔다'이다. 기관마다 보내는 키가 달라 원문을 그대로 둔다.
    report_dispatched_at  timestamp     NULL,
    report_dispatch       jsonb         NULL
);


-- -----------------------------------------------------
-- 8. 119 송수신 로그                          [F-05 N-04]
-- 전송 시도 1회에 1행. 무엇을 보냈고 무엇이 돌아왔는지 그대로 남긴다.
-- report_119 는 결과 요약(상태·시도횟수·접수번호)만 갖고 있어서
-- "언제 보냈고 왜 승계했나"를 사후에 따질 근거가 없었다.
-- 응답이 없어 재전송한 것과 거절당해 재전송한 것은 뜻이 다르다 — log_result 로 구분한다.
-- -----------------------------------------------------
CREATE TABLE fireguard.report_log (
    log_no          bigint        GENERATED BY DEFAULT AS IDENTITY,
    report_no       bigint        NOT NULL,
    log_attempt     integer       NOT NULL,
    log_endpoint    varchar(500)  NULL,
    log_request     jsonb         NULL,
    log_result      varchar(20)   NULL,
    log_http_status integer       NULL,
    log_response    jsonb         NULL,
    log_error       varchar(500)  NULL,
    log_elapsed_ms  integer       NULL,
    log_sent_at     timestamp     NULL
);


-- -----------------------------------------------------
-- 9. 사용자 활동이력                              [F-01]
-- 사용자 1명에 N행. 접속·로그아웃뿐 아니라 계정 변경과 관제 조치까지 남긴다.
-- 종류는 아래 '상태값 정의' 블록의 activity_type 참고.
--
-- activity_target_no 와 activity_detail 은 "무엇을 했는지"를 구분하려고 뒀다.
-- 종류만 있으면 화재 조치 이력이 전부 똑같이 보여서, 언제 어느 카메라 건이었는지
-- 답할 수가 없다. target 은 대상 행의 번호(event_no / user_no), detail 은
-- 화면에 그대로 띄울 한 줄 요약이다. 둘 다 없어도 되는 값이라 NULL 을 허용한다.
--
-- IP 와 User-Agent 는 의도적으로 넣지 않았다 — "언제 들어오고 나갔나"만
-- 보여주기로 한 결정이다. 나중에 필요해지면 컬럼을 더하면 되지만,
-- 그 시점의 기존 행은 전부 NULL 로 남는다는 점은 알고 있어야 한다.
--
-- 실패한 시도는 여기 쌓지 않는다. 실패는 침입 시도 기록이지 활동 이력이 아니고,
-- 섞이면 '이 사람이 무엇을 했나'를 읽을 수 없게 된다.
--
-- ⚠️ JWT 는 무상태라 서버가 로그아웃 시점을 스스로 알 수 없다. LOGOUT 행은
--    프론트가 POST /api/auth/logout 을 불러줘야만 쌓인다. 브라우저를 그냥
--    닫으면 남지 않는다 — 명시적 로그아웃만 기록되는 표다.
-- -----------------------------------------------------
CREATE TABLE fireguard.user_activity (
    activity_no        bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_no            bigint       NOT NULL,
    activity_type      varchar(20)  NOT NULL,
    activity_target_no bigint       NULL,
    activity_detail    varchar(255) NULL,
    activity_at        timestamp    NOT NULL  DEFAULT now()
);


-- =====================================================
-- 기본키
-- =====================================================
ALTER TABLE fireguard.users      ADD CONSTRAINT PK_USERS       PRIMARY KEY (user_no);
ALTER TABLE fireguard.cctv       ADD CONSTRAINT PK_CCTV        PRIMARY KEY (cctv_no);
ALTER TABLE fireguard.fire_event ADD CONSTRAINT PK_FIRE_EVENT  PRIMARY KEY (event_no);
ALTER TABLE fireguard.event_media ADD CONSTRAINT PK_EVENT_MEDIA PRIMARY KEY (media_no);
ALTER TABLE fireguard.alert      ADD CONSTRAINT PK_ALERT       PRIMARY KEY (alert_no);
ALTER TABLE fireguard.agency     ADD CONSTRAINT PK_AGENCY      PRIMARY KEY (agency_no);
ALTER TABLE fireguard.report_119 ADD CONSTRAINT PK_REPORT_119  PRIMARY KEY (report_no);
ALTER TABLE fireguard.report_log ADD CONSTRAINT PK_REPORT_LOG  PRIMARY KEY (log_no);
ALTER TABLE fireguard.user_activity ADD CONSTRAINT PK_USER_ACTIVITY PRIMARY KEY (activity_no);


-- =====================================================
-- 유니크 제약
-- 로그인 아이디 중복을 DB 에서 막는다 (ERD v4 에는 없던 것)
-- =====================================================
ALTER TABLE fireguard.users ADD CONSTRAINT UQ_USERS_USER_ID UNIQUE (user_id);


-- =====================================================
-- 검사 제약
-- user_pw 의 NOT NULL 을 푼 대가를 여기서 되받는다 — 비밀번호가 없어도 되는 건
-- 소셜 계정뿐이고, 일반 계정이 비밀번호 없이 들어오는 건 여전히 막아야 한다.
-- =====================================================
ALTER TABLE fireguard.users ADD CONSTRAINT CK_USERS_LOCAL_PW
    CHECK (user_provider <> 'LOCAL' OR user_pw IS NOT NULL);


-- =====================================================
-- 외래키
-- =====================================================
ALTER TABLE fireguard.cctv ADD CONSTRAINT FK_users_TO_cctv
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);

ALTER TABLE fireguard.fire_event ADD CONSTRAINT FK_cctv_TO_fire_event
    FOREIGN KEY (cctv_no) REFERENCES fireguard.cctv (cctv_no);

ALTER TABLE fireguard.event_media ADD CONSTRAINT FK_fire_event_TO_event_media
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.alert ADD CONSTRAINT FK_fire_event_TO_alert
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.alert ADD CONSTRAINT FK_users_TO_alert
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);

ALTER TABLE fireguard.report_119 ADD CONSTRAINT FK_fire_event_TO_report_119
    FOREIGN KEY (event_no) REFERENCES fireguard.fire_event (event_no);

ALTER TABLE fireguard.report_119 ADD CONSTRAINT FK_agency_TO_report_119
    FOREIGN KEY (agency_no) REFERENCES fireguard.agency (agency_no);

ALTER TABLE fireguard.report_log ADD CONSTRAINT FK_report_119_TO_report_log
    FOREIGN KEY (report_no) REFERENCES fireguard.report_119 (report_no);

ALTER TABLE fireguard.user_activity ADD CONSTRAINT FK_users_TO_user_activity
    FOREIGN KEY (user_no) REFERENCES fireguard.users (user_no);


-- =====================================================
-- 인덱스
-- =====================================================
CREATE INDEX IX_fire_event_01  ON fireguard.fire_event  (cctv_no, event_detected_at);
CREATE INDEX IX_event_media_01 ON fireguard.event_media (event_no, media_is_primary);
CREATE INDEX IX_alert_01       ON fireguard.alert       (event_no);
CREATE INDEX IX_report_119_01  ON fireguard.report_119  (event_no, report_sequence);
CREATE INDEX IX_report_log_01  ON fireguard.report_log  (report_no, log_attempt);

-- 화면이 항상 "이 사람의 최근 이력"을 최신순으로 뽑으므로 정렬 방향까지 맞춰 둔다
CREATE INDEX IX_user_activity_01 ON fireguard.user_activity (user_no, activity_at DESC);

-- 공간 인덱스 — 최근접 탐색(`<->` KNN)이 이걸 탄다.
-- B-tree 로는 거리 정렬을 색인할 수 없어 GiST 를 쓴다.
CREATE INDEX IX_agency_geog    ON fireguard.agency USING GIST (agency_geog);

-- 출처 고유번호는 기관을 가리키는 열쇠다. 손으로 등록한 행(NULL)은 제외한다.
CREATE UNIQUE INDEX UX_agency_source_id ON fireguard.agency (agency_source_id)
    WHERE agency_source_id IS NOT NULL;
CREATE INDEX IX_cctv_geog      ON fireguard.cctv   USING GIST (cctv_geog);

-- 진행 중인 신고가 이벤트당 하나만 있도록 DB 에서 강제한다
-- PostgreSQL 부분 인덱스 (MySQL 에는 없는 기능)
-- ⚠️ 이 상태 집합은 services/report_service.py 의 ACTIVE_STATUSES 와 반드시 같아야
--    한다. 어긋나면 출동 중인 화재에 신고가 한 번 더 나가거나(집합이 좁으면),
--    INSERT 가 유니크 위반 23505 로 터진다(집합이 넓으면).
CREATE UNIQUE INDEX UX_report_119_active ON fireguard.report_119 (event_no)
    WHERE report_status IN ('SENDING', 'ACCEPTED', 'DISPATCHED');

-- 같은 소셜 계정이 두 번 들어오지 않게. 일반(LOCAL) 계정은 provider_id 가 NULL 이라
-- 이 인덱스의 대상이 아니다 — 그래서 부분 인덱스여야 한다 (NULL 이 여럿이어도 무방).
CREATE UNIQUE INDEX UQ_USERS_PROVIDER ON fireguard.users (user_provider, user_provider_id)
    WHERE user_provider_id IS NOT NULL;


-- =====================================================
-- 테이블 주석 (pgAdmin 트리와 ERD 도구에서 한글 논리명으로 보인다)
-- =====================================================
COMMENT ON TABLE fireguard.users       IS '관리자 계정';
COMMENT ON TABLE fireguard.cctv        IS '연동 카메라';
COMMENT ON TABLE fireguard.fire_event  IS '화재 판정 결과';
COMMENT ON TABLE fireguard.event_media IS '검출 프레임과 영상 클립';
COMMENT ON TABLE fireguard.alert       IS '단계별 관리자 알림';
COMMENT ON TABLE fireguard.agency      IS '소방서';
COMMENT ON TABLE fireguard.report_119  IS '119 신고';
COMMENT ON TABLE fireguard.report_log  IS '119 송수신 로그';
COMMENT ON TABLE fireguard.user_activity IS '사용자 활동이력';


-- =====================================================
-- 컬럼 주석
-- =====================================================
COMMENT ON COLUMN fireguard.users.user_no            IS '사용자 번호';
COMMENT ON COLUMN fireguard.users.user_id            IS '로그인 아이디';
COMMENT ON COLUMN fireguard.users.user_pw            IS '비밀번호 해시';
COMMENT ON COLUMN fireguard.users.user_name          IS '이름';
COMMENT ON COLUMN fireguard.users.user_email         IS '이메일';
COMMENT ON COLUMN fireguard.users.user_phone         IS '휴대전화 번호';
COMMENT ON COLUMN fireguard.users.user_role          IS '권한 등급';
COMMENT ON COLUMN fireguard.users.user_status        IS '계정 상태';
COMMENT ON COLUMN fireguard.users.user_gender        IS '성별';
COMMENT ON COLUMN fireguard.users.user_address       IS '주소';
COMMENT ON COLUMN fireguard.users.user_provider      IS '가입 경로';
COMMENT ON COLUMN fireguard.users.user_provider_id   IS '소셜 제공자가 준 고유 식별자';
COMMENT ON COLUMN fireguard.users.user_token_valid_from IS '이 시각 이전 발급 토큰 폐기';
COMMENT ON COLUMN fireguard.users.user_created_at    IS '가입 일시';
COMMENT ON COLUMN fireguard.users.user_updated_at    IS '수정 일시';
COMMENT ON COLUMN fireguard.users.user_withdrawal_at IS '탈퇴 일시';

COMMENT ON COLUMN fireguard.cctv.cctv_no         IS '카메라 번호';
COMMENT ON COLUMN fireguard.cctv.user_no         IS '담당 사용자 번호';
COMMENT ON COLUMN fireguard.cctv.cctv_name       IS '카메라 이름';
COMMENT ON COLUMN fireguard.cctv.cctv_location   IS '설치 위치';
COMMENT ON COLUMN fireguard.cctv.cctv_address    IS '좌표를 역지오코딩한 주소 (119 신고에 싣는 값)';
COMMENT ON COLUMN fireguard.cctv.cctv_lat        IS '위도';
COMMENT ON COLUMN fireguard.cctv.cctv_lng        IS '경도';
COMMENT ON COLUMN fireguard.cctv.cctv_stream_url IS '스트림 주소';
COMMENT ON COLUMN fireguard.cctv.cctv_width      IS '영상 가로 픽셀';
COMMENT ON COLUMN fireguard.cctv.cctv_height     IS '영상 세로 픽셀';
COMMENT ON COLUMN fireguard.cctv.cctv_status     IS '카메라 상태';
COMMENT ON COLUMN fireguard.cctv.cctv_created_at IS '등록 일시';
COMMENT ON COLUMN fireguard.cctv.cctv_geog       IS '좌표점 (위경도에서 자동 생성, 공간 질의용)';

COMMENT ON COLUMN fireguard.fire_event.event_no                IS '이벤트 번호';
COMMENT ON COLUMN fireguard.fire_event.cctv_no                 IS '카메라 번호';
COMMENT ON COLUMN fireguard.fire_event.event_status            IS '판정 결과';
COMMENT ON COLUMN fireguard.fire_event.event_class             IS '검출 종류';
COMMENT ON COLUMN fireguard.fire_event.event_first_detected_at IS '최초 감지 일시';
COMMENT ON COLUMN fireguard.fire_event.event_detected_at       IS '화재 확정 일시';
COMMENT ON COLUMN fireguard.fire_event.event_detected_frames   IS '검출된 프레임 수';
COMMENT ON COLUMN fireguard.fire_event.event_threshold_frames  IS '확정 기준 프레임 수';
COMMENT ON COLUMN fireguard.fire_event.event_confidence        IS '최고 신뢰도';
COMMENT ON COLUMN fireguard.fire_event.event_is_test           IS '점검 모드 여부';
COMMENT ON COLUMN fireguard.fire_event.event_source_type       IS '이벤트 입력 종류 (CCTV_LIVE, VIDEO_TEST)';
COMMENT ON COLUMN fireguard.fire_event.event_source_metadata   IS '영상·모델·판정 설정 메타데이터';
COMMENT ON COLUMN fireguard.fire_event.event_cctv_snapshot     IS '테스트 당시 CCTV 정보 스냅샷';
COMMENT ON COLUMN fireguard.fire_event.event_processed_frames  IS 'AI가 실제 추론한 전체 프레임 수';
COMMENT ON COLUMN fireguard.fire_event.event_first_detected_offset_sec IS '영상 내 최초 검출 위치(초)';
COMMENT ON COLUMN fireguard.fire_event.event_confirmed_offset_sec IS '영상 내 화재 확정 위치(초)';
COMMENT ON COLUMN fireguard.fire_event.event_test_started_at   IS '영상 테스트 처리 시작 일시';
COMMENT ON COLUMN fireguard.fire_event.event_test_finished_at  IS '영상 테스트 처리 종료 일시';

COMMENT ON COLUMN fireguard.event_media.media_no          IS '미디어 번호';
COMMENT ON COLUMN fireguard.event_media.event_no          IS '이벤트 번호';
COMMENT ON COLUMN fireguard.event_media.media_url         IS '파일 경로';
COMMENT ON COLUMN fireguard.event_media.media_detections  IS '검출 상자 목록';
COMMENT ON COLUMN fireguard.event_media.media_confidence  IS '최고 신뢰도';
COMMENT ON COLUMN fireguard.event_media.media_captured_at IS '촬영 일시';
COMMENT ON COLUMN fireguard.event_media.media_is_primary  IS '대표 이미지 여부';
COMMENT ON COLUMN fireguard.event_media.media_is_first    IS '최초 검출 증거 이미지 여부';
COMMENT ON COLUMN fireguard.event_media.media_is_confirmation IS '화재 확정 증거 이미지 여부';
COMMENT ON COLUMN fireguard.event_media.media_frame_index IS '원본 영상의 프레임 번호';
COMMENT ON COLUMN fireguard.event_media.media_source_offset_sec IS '원본 영상 내 위치(초)';

COMMENT ON COLUMN fireguard.alert.alert_no           IS '알림 번호';
COMMENT ON COLUMN fireguard.alert.event_no           IS '이벤트 번호';
COMMENT ON COLUMN fireguard.alert.user_no            IS '수신 사용자 번호';
COMMENT ON COLUMN fireguard.alert.alert_channel      IS '발송 경로';
COMMENT ON COLUMN fireguard.alert.alert_status       IS '알림 상태';
COMMENT ON COLUMN fireguard.alert.alert_sent_at      IS '발송 일시';
COMMENT ON COLUMN fireguard.alert.alert_deadline_at  IS '취소 유예 마감 일시';
COMMENT ON COLUMN fireguard.alert.alert_responded_at IS '응답 일시';

COMMENT ON COLUMN fireguard.agency.agency_no       IS '기관 번호';
COMMENT ON COLUMN fireguard.agency.agency_name     IS '기관 이름';
COMMENT ON COLUMN fireguard.agency.agency_lat      IS '위도';
COMMENT ON COLUMN fireguard.agency.agency_lng      IS '경도';
COMMENT ON COLUMN fireguard.agency.agency_endpoint IS '신고 전송 주소';
COMMENT ON COLUMN fireguard.agency.agency_is_active IS '기관 사용 여부';
COMMENT ON COLUMN fireguard.agency.agency_source_id IS '출처 고유번호 (생활안전지도 IF_0038 objt_id). 손으로 등록한 행은 NULL';
COMMENT ON COLUMN fireguard.agency.agency_address  IS '주소 (도로명 우선, 없으면 지번)';
COMMENT ON COLUMN fireguard.agency.agency_phone    IS '대표 전화번호';
COMMENT ON COLUMN fireguard.agency.agency_geog     IS '좌표점 (위경도에서 자동 생성, 최근접 탐색용)';

COMMENT ON COLUMN fireguard.report_119.report_no             IS '신고 번호';
COMMENT ON COLUMN fireguard.report_119.event_no              IS '이벤트 번호';
COMMENT ON COLUMN fireguard.report_119.agency_no             IS '전송 대상 기관 번호';
COMMENT ON COLUMN fireguard.report_119.report_sequence       IS '승계 순번';
COMMENT ON COLUMN fireguard.report_119.report_external_id    IS '신고 식별자';
COMMENT ON COLUMN fireguard.report_119.report_trigger_reason IS '신고 발생 사유';
COMMENT ON COLUMN fireguard.report_119.report_status         IS '신고 상태';
COMMENT ON COLUMN fireguard.report_119.report_address        IS '신고 지점 주소';
COMMENT ON COLUMN fireguard.report_119.report_distance_km    IS '기관까지 거리';
COMMENT ON COLUMN fireguard.report_119.report_attempt_count  IS '전송 시도 횟수';
COMMENT ON COLUMN fireguard.report_119.reported_at           IS '전송 일시';
COMMENT ON COLUMN fireguard.report_119.report_accepted_at    IS '119 접수 확인 일시 (출동 배차 확인이 아님)';
COMMENT ON COLUMN fireguard.report_119.report_dispatched_at  IS '소방서 출동 통지 수신 일시';
COMMENT ON COLUMN fireguard.report_119.report_dispatch       IS '소방서가 보낸 출동 정보 원문 (지령번호·차량·ETA)';

COMMENT ON COLUMN fireguard.report_log.log_no          IS '로그 번호';
COMMENT ON COLUMN fireguard.report_log.report_no       IS '신고 번호';
COMMENT ON COLUMN fireguard.report_log.log_attempt     IS '몇 번째 전송 시도인가';
COMMENT ON COLUMN fireguard.report_log.log_endpoint    IS '전송한 기관 주소';
COMMENT ON COLUMN fireguard.report_log.log_request     IS '보낸 신고 본문';
COMMENT ON COLUMN fireguard.report_log.log_result      IS '전송 결과';
COMMENT ON COLUMN fireguard.report_log.log_http_status IS '응답 HTTP 상태코드 (무응답이면 없음)';
COMMENT ON COLUMN fireguard.report_log.log_response    IS '받은 응답 본문';
COMMENT ON COLUMN fireguard.report_log.log_error       IS '전송 실패 사유 (타임아웃·연결실패)';
COMMENT ON COLUMN fireguard.report_log.log_elapsed_ms  IS '요청부터 응답까지 걸린 시간(ms)';
COMMENT ON COLUMN fireguard.report_log.log_sent_at     IS '전송 일시';

COMMENT ON COLUMN fireguard.user_activity.activity_no        IS '활동 번호';
COMMENT ON COLUMN fireguard.user_activity.user_no            IS '사용자 번호';
COMMENT ON COLUMN fireguard.user_activity.activity_type      IS '활동 종류';
COMMENT ON COLUMN fireguard.user_activity.activity_target_no IS '대상 번호 (화재 이벤트·사용자)';
COMMENT ON COLUMN fireguard.user_activity.activity_detail    IS '활동 요약';
COMMENT ON COLUMN fireguard.user_activity.activity_at        IS '활동 일시';


-- =====================================================
-- 상태값 정의 (참고용, 코드에서 비교하는 값)
-- =====================================================
-- users.user_role          : ADMIN(관리자) VIEWER(조회전용)
-- users.user_status        : ACTIVE(정상) PENDING(관리자 승격 승인 대기)
--                            SUSPENDED(정지) WITHDRAWN(탈퇴)
--                            PENDING 은 권한만 기다리는 정상 계정이다 — 로그인·계정 찾기가 되고
--                            user_role 은 VIEWER 그대로다. 승인되면 ADMIN·ACTIVE 가 된다.
-- users.user_provider      : LOCAL(아이디/비밀번호) GOOGLE KAKAO NAVER
--                            LOCAL 이 아니면 user_pw 가 NULL 이고 비밀번호 로그인이 막힌다.
--                            소셜 계정의 user_id 는 '{provider소문자}_{provider_id}' 를
--                            50자로 자른 합성값이다 (아이디 유니크 제약을 지키기 위한 것).
-- cctv.cctv_status         : ACTIVE(정상) INACTIVE(중지) ERROR(오류)
-- fire_event.event_status  : PENDING(누적중) CONFIRMED(확정) DISMISSED(기준미달)
-- fire_event.event_class   : FLAME(불꽃) SMOKE(연기) FLAME_SMOKE(둘다)
-- alert.alert_channel      : PUSH(앱알림) SMS(문자)
-- alert.alert_status       : SENT(발송) READ(확인) CANCELED(취소) NO_RESPONSE(무응답)
-- report_119.report_status : SENDING(전송중) ACCEPTED(접수확인)
--                            DISPATCHED(출동 통지 수신)
--                            NO_RESPONSE(무응답으로 승계) FAILED(전송실패)
--                            진행 중으로 보는 것은 앞의 셋이고, 이벤트당 1건만
--                            존재할 수 있다 (부분 유니크 인덱스 UX_report_119_active).
--   ⚠️ DISPATCHED 는 폐기했던 이름이 **다른 뜻으로** 부활한 것이다.
--      db/migrations/001 이 옛 DISPATCHED 를 ACCEPTED 로 개명했었다.
--        001 의 DISPATCHED = '119 서버가 신고를 받았다'  → 지금의 ACCEPTED
--        007 의 DISPATCHED = '소방차가 실제로 출동했다'  (119 가 콜백으로 알려준다)
--      001 만 읽고 '지웠던 걸 왜 되살렸나' 로 헷갈리지 않도록 여기 남긴다.
-- user_activity.activity_type : LOGIN(접속) LOGOUT(로그아웃)
--                            PASSWORD_CHANGED(비밀번호 변경) PROFILE_UPDATED(프로필 수정)
--                            FIRE_CONFIRMED(화재 확인) FIRE_DISMISSED(오탐 취소)
--                            target 이 붙는 것: PROFILE_UPDATED→user_no,
--                            FIRE_CONFIRMED/FIRE_DISMISSED→event_no
-- report_log.log_result    : ACCEPTED(2xx 접수확인) REJECTED(2xx 아닌 응답)
--                            TIMEOUT(응답 없음 — 상대는 접수했을 수 있다)
--                            ERROR(연결 실패 등 전송 자체가 안 됨)
--
-- media_detections 저장 형태 (좌표는 0~1 비율, YOLO 의 xywhn)
-- [{"cls":"flame","conf":0.910,"box":[0.238,0.259,0.047,0.113]},
--  {"cls":"person","conf":0.774,"box":[0.412,0.688,0.031,0.142]}]


-- =====================================================
-- 구축 확인
-- =====================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'fireguard'
ORDER BY table_name;

select * from cctv;

